language: perl
perl:
    - "5.30"
    - "5.28"
    - "5.26"
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
before_script:
    - "echo TRAVIS_PERL_VERSION=$TRAVIS_PERL_VERSION"
    - "perlbrew install-patchperl -f"
    - "if [[ \"$TRAVIS_PERL_VERSION\" == \"5.12\" ]]; then echo \"[custom] installing Perl 5.12\"; perlbrew install -n -v -j 2 --switch perl-5.12.0; perlbrew install-cpanm -f; perl use 5.12.0; fi; "
    - "if [[ \"$TRAVIS_PERL_VERSION\" == \"5.10\" ]]; then echo \"[custom] installing Perl 5.10\"; perlbrew install -n -v -j 2 --switch perl-5.10.0; perlbrew install-cpanm -f; perl use 5.10.0; fi; "
    - "perl -v"
    - "cpanm --notest --installdeps ."
script:
    - "prove -v -Ilib t/"
