language: perl
perl:
    - "5.30"
    - "5.28"
    - "5.26"
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
before_script:
    - "echo TRAVIS_PERL_VERSION=$TRAVIS_PERL_VERSION"
    - "if [[ \"$TRAVIS_PERL_VERSION\" == \"5.12\" ]]; then echo \"[custom] installing Perl 5.12\"; perl install perl-5.12.0 && perl use 5.12.0; fi; "
    - "cpanm --notest --installdeps ."
script:
    - "prove -v -Ilib t/"
